module.exports = {
	free: {
		src:  [
			'**',
			'!bin/**',
			'!build/**',
			'!__grunt-tasks-config__/**',
			'!node_modules/**',
			'!tests/**',
			'!wpcs/**',
			'!.git/**',
			'!gruntfile.js',
      '!package.json',
      '!.eslintrc.js',
      '!package-lock.json',
			'!.gitignore',
			'!.ftpauth',
			'!.travis.yml',
			'!travis-examples/**',
			'!phpunit.xml',
			//'!readme.md',
			'!**/*.db',
      '!patches/**',
      '!functions/init-pro.php',
      '!assets/czr/fmk/**',
      '!assets/front/css/dev-common.css',
      '!assets/front/css/_parts/**',
      '!assets/front/css/dev-responsive.css',
      '!assets/front/css/main-rtl.css',
      '!assets/front/js/_parts/**',
      '!assets/front/js/_front_js_fmk/**',
      '!lang_pro/**',
      //'!assets/front/css/dev-font-awesome.css',
      '!npm-debug.log',
      '!functions/czr-modules/widget-zones/assets/js/_dev'
		],
		dest: 'build/<%= pkg.name %>/'
	},
  pro: {
    src:  [
      '**',
      '!bin/**',
      '!build/**',
      '!__grunt-tasks-config__/**',
      '!node_modules/**',
      '!tests/**',
      '!wpcs/**',
      '!.git/**',
      '!.travis.yml',
      '!travis-examples/**',
      '!phpunit.xml',
      '!**/*.db',
      '!patches/**',
      '!.ftpauth',
      '!.gitignore',
      '!gruntfile.js',
      '!package.json',
      '!.eslintrc.js',
      '!package-lock.json',
      '!readme.md',
      '!readme.txt',
      '!screenshot.png',
      '!style.css',
      //'!functions/admin/class-tgm-plugin-activation.php',
      '!assets/front/css/dev-common.css',
      '!assets/front/css/_parts/**',
      '!assets/front/css/dev-responsive.css',
      '!assets/front/css/main-rtl.css',
      '!assets/front/js/_parts/**',
      '!assets/front/js/_front_js_fmk/**',
      '!languages/hueman.pot',
      '!lang_pro/**',
      //'!assets/front/css/dev-font-awesome.css',
      '!npm-debug.log',
      '!functions/czr-modules/widget-zones/assets/js/_dev'
    ],
    dest: '../hueman-pro/'
  },
  pro_lang: {
    cwd : 'lang_pro/',
    src: [
      '*.po'
    ],
    expand: true,
    dest: '../hueman-pro/languages'
  }
};